trigger: 
  - development 
pr: none

pool:
  vmImage: "ubuntu-latest"
   
resources:
  repositories:
    - repository: "ThermaxDevOpsAutomation"
      type: "git"
      name: "Customer Portal/ThermaxDevOpsAutomation"
      ref: "main"  

stages: 
 - stage: "DEV"
   jobs:
    - template: CI/Build&PushDocker.yml@ThermaxDevOpsAutomation
      parameters:
        useSonar: false
        sonarOrganization: NA
        appname: tcpScheduler
        sonarKey: ThermaxCP
        containerRegistry: acrcinthermaxdev.azurecr.io
        environmentBranch: development
        environmentName: Dev
        dockerRegistryServiceConnection: Thermaxdockerdev
        imageRepository: dev/Scheduler
        MAVEN_OPTS: '-Dmaven.test.skip=true'

    - template: CD/k8s-deploy.yml@ThermaxDevOpsAutomation
      parameters:
          appName: tcpScheduler
          environmentName: Dev
          environmentBranch: Development
          filepath: 'Devops/k8s-Scheduler.yaml'
          containerreg: acrcinthermaxdev.azurecr.io
          imagerepo: dev/Scheduler
          k8ssvcconn: Thermaxk8sdev 
          springProfilesActive: dev
          dbHost: ""
          dbUser: ""
          dbPassword: ""
          dbName: ""