apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpschedulers
  labels:
    app: tcpschedulers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcpschedulers
  template:
    metadata:
      labels:
        app: tcpschedulers
    spec:
      containers:
      - name: tcpschedulers
        image: #{imagepath}#:#{imagetag}

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: #{springProfilesActive}#

        ports:
        - containerPort: 7072

      storage:
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
---
apiVersion: v1
kind: Service
metadata:
  name: tcpschedulers
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7072
  selector:
    app: tcpschedulers