apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: tcpschedulers
spec:
  resources:
    requests:
      storage: 2G	
  accessModes:
    - ReadWriteMany
  storageClassName: storageclassshared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpschedulers
  labels:
    app: tcpschedulers
spec:
  replicas: #{replica}#
  selector:
    matchLabels:
      app: tcpschedulers
  template:
    metadata:
      labels:
        app: tcpschedulers
      spec:
      - name: tcpschedulers
        image: #{imagepath}#:#{imagetag}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: #{springProfilesActive}#
        ports:
        - containerPort: 7072
        volumeMounts:
            - mountPath: /var/tcp/tcp-schedulers 
              name: tcpschedulers
              subPath: tcpschedulers

      volumes:
        - name: tcpschedulers
          persistentVolumeClaim:
            claimName: tcpschedulers
---
apiVersion: v1
kind: Service
metadata:
  name: tcpschedulers
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7072
  selector:
    app: tcpschedulers
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tcp-cron
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name:  cronjob
              image: #{imagepath}#:#{imagetag}#
              command: ["/bin/bash"]
              args: ["-c","bash /home/app-logging.sh && sleep 600"]
              volumeMounts:
                - mountPath: /opt/scripts
                  name: tcpschedulers-app-logging
                  subPath: tcpschedulers-app-logging

          volumes:
            - name: tcpschedulers-app-logging
              persistentVolumeClaim:
                claimName: tcpschedulers
          restartPolicy: OnFailure    