apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpschedulers
  labels:
    app: tcpschedulers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcpschedulers
  template:
    metadata:
      labels:
        app: tcpschedulers
    spec:
      containers:
      - name: tcpschedulers
        image: #{imagepath}#:#{imagetag}

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: #{springProfilesActive}#
          
        ports:
        - containerPort: 7072
     # imagePullSecrets:
     #   - name: dockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: tcpschedulers
  annotations:
  ##   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
   #  service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-subnet2"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7072
  selector:
    app: tcpschedulers
    
    
    