trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"
   
resources:
  repositories:
    - repository: "ThermaxDevOpsAutomation"
      type: "git"
      name: "Customer Portal/ThermaxDevOpsAutomation"
      ref: "main"  

stages: 
 - stage: "DEV"
   condition: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
   variables:
   - group: DB-Dev
   jobs:
    - template: CI/Build&PushDocker.yml@ThermaxDevOpsAutomation
      parameters:
        useSonar: false
        sonarOrganization: NA
        appname: Scheduler 
        sonarKey: ThermaxCP
        containerRegistry: acrcinthermaxdev.azurecr.io
        environmentBranch: development
        environmentName: Dev
        dockerRegistryServiceConnection: Thermaxdockerdev
        imageRepository: dev/Scheduler
        MAVEN_OPTS: '-Dmaven.test.skip=true'

    - template: CD/k8s-deploy.yml@ThermaxDevOpsAutomation
      parameters:
          appName: tcpscheduler
          environmentName: Dev
          environmentBranch: Development
          filepath: 'Devops/k8s-salesforce.yaml'
          containerreg: acrcinthermaxdev.azurecr.io
          imagerepo: dev/salesforcemanagement
          k8ssvcconn: Thermaxk8sdev 
          springProfilesActive: dev
          dbHost: $(dbHost)
          dbUser: $(dbUsername)
          dbPassword: $(dbPassword)
          dbName: $(dbName)