spring:
  application:
    name: THERMAX-SFDC-INTERFACE
  datasource:
    url: jdbc:postgresql://azpgsql-cin-thermax-dev.postgres.database.azure.com:5432/thermaxcp?user=thermax@azpgsql-cin-thermax-dev&password=Password@12345&sslmode=require
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
  batch:
    job:
      enabled: false
    initialize-schema: always


management:
  endpoint:
    health:
      group:
        liveliness:
          include: livenessProbe,cacheCheck
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 7071
  shutdown: graceful

resilience4j:
  ratelimiter:
    rateLimiterAspectOrder: 1
    instances:
      getAccountsRateLimit:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 1s
  circuitbreaker:
    circuitBreakerAspectOrder: 2
    instances:
      commonClientRateLimit:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 1s
      commonClientCB:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 1s
      updateAccountCB:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 1s
      getAccountInfoCB:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 1s

  retry:
    retryAspectOrder: 3
    instances:
      updateAccountRetry:
        max-attempts: 5
        wait-duration: 2s
        retry-exceptions: org.springframework.web.client.ResourceAccessException

feign:
  client:
    enquiry:
      base-url: http://localhost:8080
      orders-url: /enquiryApi/api/v1/scheduler/orders
      order-items-url: /enquiryApi/api/v1/scheduler/orderItems
      order-status-url: /enquiryApi/api/v1/scheduler/orderStatus
    assets:
      base-Url: https://apim-cin-thermax-dev.azure-api.net
      recommendations-url: /assetsApi/recommendations/recommendationFromSdfc
      assets-url: /assetsApi/recommendations/assetFromSdfc
    url: https://thermax--tmxdev.my.salesforce.com/services
    fileUploadUrl: https://apim-cin-thermax-dev.azure-api.net/fileuploadapi
    orderHeadersUrl: https://mobility.thermaxglobal.com/tmx_intg/

sfdc:
  grant-type: password
  client-id: 3MVG9Se4BnchkASk9vur9uLifnr7DiLDaGX4u2f7VkdNCwemsfmOug1loAmKwRLurEKuM5FHwFgUPJJcsXwGB
  client-secret: 7785F6398BBDF7F4691ECC097992FF832595A2B55BFC8A877F82A69CE3A39682
  username: cp.integration.user@nagarro.com
  password: Salesforce@123
sfdcorders:
  grant-type: password
  username: Thermax.CPIntegrationTestUser
  password: SaENw#@2MCJd
  INSTANCE: TMXTESTINST


logging:
  level:
    com.thermax.cp.salesforce: DEBUG
    org.springframework: DEBUG
    org.springframework.web.servlet: DEBUG
