spring:
  application:
    name: THERMAX-SFDC-INTERFACE

management:
  endpoint:
    health:
      group:
        liveliness:
          include: livenessProbe,cacheCheck
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 7071
  shutdown: graceful

resilience4j:
  ratelimiter:
    rateLimiterAspectOrder: 1
    instances:
      getAccountsRateLimit:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 1s
  circuitbreaker:
    circuitBreakerAspectOrder: 2
    instances:
      updateAccountCB:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 1s
      getAccountInfoCB:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 1s

  retry:
    retryAspectOrder: 3
    instances:
      updateAccountRetry:
        max-attempts: 5
        wait-duration: 2s
        retry-exceptions: org.springframework.web.client.ResourceAccessException

feign:
  client:
    enquiry:
      base-url: tcpenquirymanagement
      orders-url: /enquiryApi/api/v1/scheduler/orders
      order-items-url: /enquiryApi/api/v1/scheduler/orderItems
      order-status-url: /enquiryApi/api/v1/scheduler/orderStatus
      opportunity-contact-role-url: /enquiryApi/api/v1/scheduler/opportunityContactRole
      thermax-users-url: /enquiryApi/api/v1/scheduler/thermaxUsers
      eligible-spares-service-url: /enquiryApi/api/v1/eligibleSparesServices/scheduler
      pricebook-url: /enquiryApi/api/v1/pricebook/scheduler
    assets:
      base-Url: tcpassets
      recommendations-url: /assetsApi/fileReader/recommendationFromSfdc
      assets-url: /assetsApi/fileReader/assetFromSfdc
      asset-history-url: /assetsApi/fileReader/assetHistoryFromSfdc
      services-url: /assetsApi/fileReader/servicesFromSfdc
      spares-url: /assetsApi/fileReader/sparesFromSfdc
      service-log-url: /assetsApi/fileReader/serviceLogFromSfdc
    order-status:
      base-url: https://mobility.thermaxglobal.com/tmx_intg
      get-status: /api/cp/tmx_erp/get_order_status/
    accounts:
      base-Url: tcpaccountmanagement
      accounts-url: /accountsApi/accounts/accountsFromSdfc
    url: https://thermax.my.salesforce.com/services
    fileUploadUrl: tcp-fileuploader

sfdc:
  grant-type: password
  client-id: 3MVG9d8..z.hDcPKwCmbHWfOYwjXz41QyY7UK5w8d2cALQZE5wRax7QPFgIDa3T_.CAo5wVGIMvcicZBx7QtW
  client-secret: 3DBC2AE6CEB57BBF6F87F60FDF01F424F6CBB21B232BDAFC08A3D7D8CEA622B0
  username: nagarro_intadmin@thermaxprod.com
  password: Delhi@123
sfdcorders:
  grant-type: password
  username: Thermax.CPIntegrationProdUser
  password: SaENw#@2$MCJdxks
  INSTANCE: TMXPRODINST

